language: node_js
node_js: 
  - "8.1.2"

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - cd functions
  - yarn install
  - yarn run test
  - cd ..

script :

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --only functions

notifications:
  email :
    on_failure: tonmanna@gmail.com
    on_success: tonmanna@gmail.com