language: node_js
node_js: 
  - "8.1.2"

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - cd functions
  - yarn install
  - yarn run test

script :

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email :
    on_failure: tonmanna@gmail.com
    on_success: tonmanna@gmail.com